### PR TITLE
kjspkg-go

### PR DESCRIPTION
**Pull request by tizu69**
okay this is not feature complete aight?

- [x] commands ([x] = I think its fine)
  - [x] `install`
  - [x] `remove`
  - [x] `update`
  - [x] `updateall`
  - [x] `list`: no --count, count is always displayed
  - [x] `pkg`
  - [x] `fetch`: no --script
  - [x] `listall`: no --count, count is always displayed
  - [x] `search`
  - [x] `refresh`: "not implemented" (exit 0), hidden
  - [x] `init`: no --cancreate, gcast approved
  - [x] `uninit`
  - [x] `help`: unimplemented
  - [x] `dev`
    - [x] init
    - [x] `run`
    - [x] `dist`
    - [x] `test`: "not implemented" (exit 0), hidden, gcat approved
  - [x] `gui`: "not implemented" (exit 0), hidden
- [x] code cleanup: I did some, it ain't much but it's honest work
- [x] README!
- [x] installation script
  - [ ] ~~possibly also aur n shit~~
  - [ ] ~~shell autocomplete maybe?~~

the codebase is also kinda a mess rn because me and gcast aren't the same person :) so I made decisions I later considered weird but didn't change.. will do tmr

### CODE REVIEW

**Comment by RedstoneWizard08** [comment]
@tizu69 why? also pls use new API kthxbye

**Comment by tizu69** [comment]
> @tizu69 why? also pls use new API kthxbye

i dont like rust

**Comment by RedstoneWizard08** [comment]
lmao
also pls do use the new API i want to move everything to it because ITS NOT A FRICKING JSON FILE

**Comment by tizu69** [comment]
> lmao also pls do use the new API i want to move everything to it because ITS NOT A FRICKING JSON FILE

the entire point of this is to move to something that isnt rust (but different enough from gcats version for job security™)
(also cmon jsons arent that bad)

so no, I will not. gcat gets to decide :3

**Comment by RedstoneWizard08** [comment]
> (also cmon jsons arent that bad)

JSONs are bad if you use it as a database, it becomes extremely hard to add any new packages

> the entire point of this is to move to something that isnt rust

Why? I've spent the past few weeks of my life working on this, is it not good enough for you?

**Comment by RedstoneWizard08** [comment]
Also, the JSON file version requires essentially spamming GitHub's API whenever someone lists packages, since it doesn't have any metadata in it. A real database grabs the metadata and everything with a single `SELECT * FROM packages;` query.

**Comment by tizu69** [comment]
> JSONs are bad if you use it as a database, it becomes extremely hard to add any new packages

that is very fair. but it works for this, change my mind. this doesnt have 20k packages you have to maintain. writing a simple thingy that lets you `kjspkg dev publish` that creates a pr or whatever was something i planned either way :3

> and manual approval on a PR-by-PR basis is slow and annoying for everyone

does your thing not have moderation? I mean sure, its for kjs packages, but still

> [is it not good enough for you?](https://github.com/user-attachments/assets/d8de76a5-0d7c-4a56-8a30-f11d5762088a)

> written almost 19k lines of code

also wtf

> Also, the JSON file version requires essentially spamming GitHub's API whenever someone lists packages

yesn't. listing packages is a single request to get the json? noone does a `kjspkg pkg amogus` on every package :)
yes that doesn't fetch metadata, but imo thats fine with the scale of this project :3333333

> Why? I've spent the past few weeks of my life working on this

cool, I've spent the past few days of my life working on this.
either I die a few days earlier or you do.

> A real database grabs the metadata and everything with a single `SELECT * FROM packages;` query.

I know how SQL works :)

**Comment by RedstoneWizard08** [comment]
> does your thing not have moderation? I mean sure, its for kjs packages, but still

I'm planning to add it soon, and pressing a single button is much faster than merge conflicts, not to mention the ease of adding more moderators

> yes that doesn't fetch metadata, but imo thats fine with the scale of this project :3333333

True, and I am taking an approach for allowing it to grow into a much larger scale.

>> written almost 19k lines of code

> also wtf

Yeah. I have. It's very complex.

**Comment by tizu69** [comment]
> True, and I am taking an approach for allowing it to grow into a much larger scale.

smh 
 
> Yeah. I have. It's very complex.

complex doesn't necessarily make it good

**Comment by RedstoneWizard08** [comment]
> complex doesn't necessarily make it good

Very true! There's still a good number of things to implement, and it's only going to grow larger, but at least it'll be stable (hopefully).

> smh

You got a problem with it?

**Comment by tizu69** [comment]
> Very true! There's still a good number of things to implement, and it's only going to grow larger

idk what you did but 80% of my crappy code was compat with the gcat format, so what the fuck did you do to bring it up to 19k???

> You got a problem with it?

that's not gonna happen within the next 10 years. gcat asked for a CLI rewrite, not an everything refactor.

**Comment by RedstoneWizard08** [comment]
> idk what you did but 80% of my crappy code was compat with the gcat format, so what the fuck did you do to bring it up to 19k???

You forget there's also the backend, CLI, database, and a crap load of code for all of that to work.

**Comment by RedstoneWizard08** [comment]
> gcat asked for a CLI rewrite

So what, are we going to present our products to G_cat and let him choose the best one like a cooking show?

**Comment by tizu69** [comment]
> You forget there's also the backend, CLI, database, and a crap load of code for all of that to work.

well theres your issue ig

> So what, are we going to present our products to G_cat and let him choose the best one like a cooking show?

yep :)

**Comment by RedstoneWizard08** [comment]
> well theres your issue ig

I don't think it's an issue.

**Comment by RedstoneWizard08** [comment]
Here. This is your repo:
[Lines of code](https://tokei.rs/b1/github/tizu69/kjspkg?style=for-the-badge&label=Lines+of+code)

**Comment by tizu69** [comment]
> Here. This is your repo:
> 
> [Lines of code](https://tokei.rs/b1/github/tizu69/kjspkg?style=for-the-badge&label=Lines+of+code)

Screenshot_20241116-080226

**Comment by tizu69** [comment]
lgtm

**Pull request merged**
