### PR TITLE
hamter havoc

### PR DESCRIPTION
**Pull request by bradisatomato**

### CODE REVIEW

**Comment by Gcat101** [comment]
image

version should be `10`, not `"1.20"`

**Comment by Gcat101** [comment]
config does not get downloaded along with the script, so hopefully this works with the default one kjs provides :pray:

**Comment by bradisatomato** [comment]
> image
> 
> version should be `10`, not `"1.20"`

ohh ok

**Comment by Gcat101** [comment]
image

without the quotes :trollface:

**Comment by tizu69** [comment]
skibidi

**Comment by bradisatomato** [comment]
> image
> 
> without the quotes :trollface:

💀

**Comment by RedstoneWizard08** [comment]
@bradisatomato can I ask you to publish this to the new KJSPKG as well? See https://kjspkg-uwqx.shuttle.app/install and https://github.com/RedstoneWizard08/kjspkg/wiki/Uploading-a-package for guides on installing & using the CLI

**Pull request merged**
